### ISSUE TITLE
[Question] 1.21 Penomior

### ISSUE THREAD

**Issue by makumaku1974** [MrSypz/Penomior#1]
Is this mod inspired by that game called Fear and Hunger? or just normal JRPG games. 

This is too cool and would wish to add it with my modpack if that is okay?

**Comment by MrSypz** [comment]
Sure go ahead, It inspire from black desert enchant and combat

**Comment by makumaku1974** [comment]
> Sure go ahead, It inspire from black desert enchant and combat

Cool! Also a suggestion that a bug is occuring when mobs spawn for some reason.  I will add this back in when it is fixed.
