### ISSUE TITLE
[FEATURE] Penomior Dynamic Config for Modded Weapons and Armor.

### ISSUE THREAD

**Issue by makumaku1974** [MrSypz/Penomior#11]
Instead of you coding other mods for compatibility. Why not implement the code from Crital to Penomior. 

So players like me can do a custom configuration with other modded weapons and armor.

**Comment by MrSypz** [comment]
It already have
penomior is the first mod that have

**Comment by MrSypz** [comment]
![image](https://github.com/user-attachments/assets/8dd34893-8fdb-4254-a9af-420ea0ab6ed0)

**Comment by makumaku1974** [comment]
> ![image](https://private-user-images.githubusercontent.com/123331225/350748369-8dd34893-8fdb-4254-a9af-420ea0ab6ed0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1NTM0NjEsIm5iZiI6MTcyMTU1MzE2MSwicGF0aCI6Ii8xMjMzMzEyMjUvMzUwNzQ4MzY5LThkZDM0ODkzLThmZGItNDI1NC1hOWFmLTQyMGVhMGFiNmVkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMVQwOTEyNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Yzc2MDAxM2ZmMmMxZGU4YjFjNWMxNjg0NDkyMTYyYjVjNTI0YWQ2M2VmNTQ2NTY3YjM5YmM1MjRiNzhhNWQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FsGPCXBv7mxrVA8RgXFBYFCBkPFH4B9P0jLs6UozKxU)

So that's why. I didnt understood at first to be fair. Meanwhile, was busy creating a animated resourcepack for your mods and will gather some on other mods.

**Comment by MrSypz** [comment]
I think you're right. I'll add a base data structure once I finish fixing the mob evasion and accuracy.

**Comment by makumaku1974** [comment]
> I think you're right. I'll add a base data structure once I finish fixing the mob evasion and accuracy.

for Vanilla Minecraft it should be by default. For modded, it will be our way to configure it.
