### ISSUE TITLE
[BUG] It's a bit weird in the latest update.

### ISSUE THREAD

**Issue by makumaku1974** [MrSypz/Penomior#12]
Somehow, sword attack no, any attack in melee is faster in this version and feels like a curse.
Evasion is dead, Skeletons always hits and crits.
I think it became worse than the last version. 
Instead of removing the vanilla version that has been set by default. Only the modded versions should be allowed to be configured.

**Comment by MrSypz** [comment]
0.1.7 or 0.1.6

**Comment by makumaku1974** [comment]
> 0.1.7 or 0.1.6

0.1.7

**Comment by MrSypz** [comment]
I reupload the version on modrinth, Maybe I upload the old one instead of fixing one

**Comment by makumaku1974** [comment]
> I reupload the version on modrinth, Maybe I upload the old one instead of fixing one

is this the same version with 0.2.0?

**Comment by makumaku1974** [comment]
just to be sure
