### ISSUE TITLE
[SUGGESTION] When a mob has spawned, health numbers appear and should be removed for optimization issues.

### ISSUE THREAD

**Issue by makumaku1974** [MrSypz/Penomior#5]

**Comment by MrSypz** [comment]
Fix I think the damage number is base on user now my mod are only handle for text only, (I can't find anymod to do that so I need to leave that xD)

**Comment by makumaku1974** [comment]
Please use Jade as damage indicator because it shows hearts... but what i meant is that when they spawn it shows health numbers like 20 for Zombie, 40 for Enderman, or 100 for Iron Golem. The reason I reported it is on some occassions basically harder difficulty mods. It tends to keep spawning more mobs like hostiles.

**Comment by makumaku1974** [comment]
btw my bad about saying using the latest version because I haven't yet im about to test it now.
