### ISSUE TITLE
[COMPATIBILITY] I-frames with Zombies from Contagion mod still infects the player despite having evasion.

### ISSUE THREAD

**Issue by makumaku1974** [MrSypz/Penomior#6]
If this is not evasions problem then I would report this back to Contagion mod.

**Comment by MrSypz** [comment]
I just look into contagion code it use callback even it excute before my code, So it normally apply but it good to know cuz many mod maybe use callback even that mean a lot of mod can do, But is that Contagion mod can apply a effect even player not take any damage? that so op

**Comment by makumaku1974** [comment]
> I just look into contagion code it use callback even it excute before my code, So it normally apply but it good to know cuz many mod maybe use callback even that mean a lot of mod can do, But is that Contagion mod can apply a effect even player not take any damage? that so op

I actually helped the Contagion mod tbh lol. But if there are errors from that mod I could try say to the dev.

**Comment by MrSypz** [comment]
> > I just look into contagion code it use callback even it excute before my code, So it normally apply but it good to know cuz many mod maybe use callback even that mean a lot of mod can do, But is that Contagion mod can apply a effect even player not take any damage? that so op
> 
> I actually helped the Contagion mod tbh lol. But if there are errors from that mod I could try say to the dev.

My mod is inject code after callback but If the dev is change the method that apply the effect like if take damage then start to excute cuz my evasion is ignore all damage (like creative), or maybe I'll contact him and fix the method

**Comment by makumaku1974** [comment]
> > > I just look into contagion code it use callback even it excute before my code, So it normally apply but it good to know cuz many mod maybe use callback even that mean a lot of mod can do, But is that Contagion mod can apply a effect even player not take any damage? that so op
> > 
> > 
> > I actually helped the Contagion mod tbh lol. But if there are errors from that mod I could try say to the dev.
> 
> My mod is inject code after callback but If the dev is change the method that apply the effect like if take damage then start to excute cuz my evasion is ignore all damage (like creative), or maybe I'll contact him and fix the method

That's great, I already referred this issue to him.

**Comment by MrSypz** [comment]
OK it now fix

**Comment by makumaku1974** [comment]
Somehow this is still re occurring if you dont mind some logs though.

https://mclo.gs/vXqe1ie

Is this really Nyf's Spiders problem?

**Comment by MrSypz** [comment]
is zombie still infects player?, I test it work normally only apply when play is take a damage?
at least if you got any problem video it more helpful for me to spot a bug
![Screenshot 2024-07-19 124512](https://github.com/user-attachments/assets/83221b39-67df-4005-95dd-19f5d6a28c3a)
and I test with nyf it not crash it work normally

**Comment by makumaku1974** [comment]
the problem is that video here is too minimized cant send over 10 megabytes.

**Comment by makumaku1974** [comment]
I've also reported the Contagion mod because i got killed by the infection which is literally not by 600 seconds. 600 seconds is required for you the be killed by an Infection from Zombies. But it didnt reach 600 seconds it was cut half or less. So once you get infected twice. You instantly die from the effect of the infection. Let alone it will NOT be reset after dying.

**Comment by makumaku1974** [comment]
Also, You missed out two mobs which is the Husk and Drowned.

**Comment by MrSypz** [comment]
> Also, You missed out two mobs which is the Husk and Drowned.

What?

https://github.com/user-attachments/assets/36e4eb4d-0de9-41c9-a7cb-194a7c2f699b

**Comment by makumaku1974** [comment]
> > Also, You missed out two mobs which is the Husk and Drowned.
> 
> What?
> 
>  24utQRk.-.Imgur.mp4

IM SHOCK AND IN AWE...

**Comment by makumaku1974** [comment]
> > Also, You missed out two mobs which is the Husk and Drowned.
> 
> What?
> 
>  24utQRk.-.Imgur.mp4

Did you have commands to instantly enhance evasion on your armor so i could check mine too.

**Comment by makumaku1974** [comment]
I got infected LMFAO

![image](https://github.com/user-attachments/assets/ecf1ed9c-96d8-430b-9e04-8fba61dbd88b)

**Comment by MrSypz** [comment]
Wait for contagion update his mod

**Comment by makumaku1974** [comment]
> Wait for contagion update his mod

what is your version then.

**Comment by makumaku1974** [comment]
> > Also, You missed out two mobs which is the Husk and Drowned.
> 
> What?
> 
>  24utQRk.-.Imgur.mp4

the "MISS" on mine is not even rendering.... could be a bug from a mod rewriting it lemme remove some for now.

**Comment by MrSypz** [comment]
> > > Also, You missed out two mobs which is the Husk and Drowned.
> > 
> > 
> > What?
> > 24utQRk.-.Imgur.mp4
> 
> the "MISS" on mine is not even rendering.... could be a bug from a mod rewriting it lemme remove some for now.

mob are not render missing that my video I just rewrite to debug if it work
Particle it'll only render when player attack not for mob

**Comment by makumaku1974** [comment]
> > > > Also, You missed out two mobs which is the Husk and Drowned.
> > > 
> > > 
> > > What?
> > > 24utQRk.-.Imgur.mp4
> > 
> > 
> > the "MISS" on mine is not even rendering.... could be a bug from a mod rewriting it lemme remove some for now.
> 
> mob are not render missing that my video I just rewrite to debug if it work Particle it'll only render when player attack not for mob

why not implement that it looks very rpg in my opinion.

**Comment by makumaku1974** [comment]
> > > > Also, You missed out two mobs which is the Husk and Drowned.
> > > 
> > > 
> > > What?
> > > 24utQRk.-.Imgur.mp4
> > 
> > 
> > the "MISS" on mine is not even rendering.... could be a bug from a mod rewriting it lemme remove some for now.
> 
> mob are not render particle ,in that my video I just debug to see is it really work, Particle it'll only render when player attack not for mob

BTW sorry for causing a lot of work bro. I already found the bug!! So Sorry again :3 .  It was from Slow Your Roll.
