### ISSUE TITLE
[BUG] Where are the numbers? Damage Numbers Specifically.

### ISSUE THREAD

**Issue by makumaku1974** [MrSypz/Penomior#7]
I was wondering where did the damage numbers went. btw  i have the latest update.

**Comment by makumaku1974** [comment]
https://github.com/user-attachments/assets/fffa8de1-79a4-4ec9-9f55-114de24895d6

**Comment by MrSypz** [comment]
I already said damage indicator are now base on users mod, only special event will pop-up like miss,crit,back attack, etc..

**Comment by makumaku1974** [comment]
Ahh got it. Btw does your other syp hud have dmg indicators?

**Comment by MrSypz** [comment]
Nope I'm not good at making that thing I recommend use other dev it have better than mine> Ahh got it. Btw does your other syp hud have dmg indicators? dmg numbers?

**Comment by makumaku1974** [comment]
> Nope I'm not good at making that thing I recommend use other dev it have better than mine> Ahh got it. Btw does your other syp hud have dmg indicators? dmg numbers?

I think what you removed from penomior... re add it to Syphud. Since it'll be better cramped in there than penomior. Also Food Bar could be changed. Compatibility with Tough As Nail's Temperature which is located at the middle.

**Comment by MrSypz** [comment]
> > Nope I'm not good at making that thing I recommend use other dev it have better than mine> Ahh got it. Btw does your other syp hud have dmg indicators? dmg numbers?
> 
> I think what you removed from penomior... re add it to Syphud. Since it'll be better cramped in there than penomior. Also Food Bar could be changed. Compatibility with Tough As Nail's Temperature which is located at the middle. Where the Oxygen Bubble too is located, might conflict together.

Tough As Nails isn't compatible with many mods that modify the HUD So I don't think it worth to fix when I play I just disable UI feature and use only sort feature instead, And food bar is still in progess.

**Comment by makumaku1974** [comment]
> > > Nope I'm not good at making that thing I recommend use other dev it have better than mine> Ahh got it. Btw does your other syp hud have dmg indicators? dmg numbers?
> > 
> > 
> > I think what you removed from penomior... re add it to Syphud. Since it'll be better cramped in there than penomior. Also Food Bar could be changed. Compatibility with Tough As Nail's Temperature which is located at the middle. Where the Oxygen Bubble too is located, might conflict together.
> 
> Tough As Nails isn't compatible with many mods that modify the HUD So I don't think it worth to fix when I play I just disable UI feature and use only sort feature instead, And food bar is still in progess.

you dont have to fix it, but put a config for oxygen meter for customization like x and y positioning. I'll be adapting the problem since they still have alot of errors with Tough As Nails.

**Comment by MrSypz** [comment]
> > > > Nope I'm not good at making that thing I recommend use other dev it have better than mine> Ahh got it. Btw does your other syp hud have dmg indicators? dmg numbers?
> > > 
> > > 
> > > I think what you removed from penomior... re add it to Syphud. Since it'll be better cramped in there than penomior. Also Food Bar could be changed. Compatibility with Tough As Nail's Temperature which is located at the middle. Where the Oxygen Bubble too is located, might conflict together.
> > 
> > 
> > Tough As Nails isn't compatible with many mods that modify the HUD So I don't think it worth to fix when I play I just disable UI feature and use only sort feature instead, And food bar is still in progess.
> 
> you dont have to fix it, but put a config for oxygen meter for customization like x and y positioning. I'll be adapting the problem since they still have alot of errors to fix with Tough As Nails.

https://github.com/MrSypz/BugReport/issues
put a feature or request in it pls I'll look what your request❤️
