### ISSUE TITLE
[Vic's Point Blank] Support Compatibility 

### ISSUE THREAD

**Issue by makumaku1974** [MrSypz/Penomior#9]
It's a recently updated mod for fabric 1.21

![image](https://github.com/user-attachments/assets/61734547-2b6b-472f-ad8c-a800fad719e3)

**Comment by MrSypz** [comment]
wdym? it already base on user config it a data driven now

**Comment by makumaku1974** [comment]
> wdym? it already base on user config it a data driven now

i meant the refining sorry.

**Comment by makumaku1974** [comment]
> wdym? it already base on user config it a data driven now

but i still able to enhance right??? without missing? like this video im about to show.

**Comment by makumaku1974** [comment]
Lower the volume too becoz it's loud.
https://github.com/user-attachments/assets/de38596f-2dc8-45f9-957a-eb574605039c

**Comment by MrSypz** [comment]
> > wdym? it already base on user config it a data driven now
> 
> but i still able to enhance right??? without missing? like this video im about to show.

just write a config and vic mod don't have equipment slot it'll not apply any data

**Comment by makumaku1974** [comment]
> > > wdym? it already base on user config it a data driven now
> > 
> > 
> > but i still able to enhance right??? without missing? like this video im about to show.
> 
> just write a config and vic mod don't have equipment slot it'll not apply any data

ahh I see, btw i asked about your contagion version... please tell.

**Comment by MrSypz** [comment]
> > > > wdym? it already base on user config it a data driven now
> > > 
> > > 
> > > but i still able to enhance right??? without missing? like this video im about to show.
> > 
> > 
> > just write a config and vic mod don't have equipment slot it'll not apply any data
> 
> ahh I see, btw i asked about your contagion version... please tell.

Vic's Point Blank don't have equipment slot so it not gonna compatible
